import express from "express";
import authRouter from "./routes/auth.routes.js";
import tourRouter from "./routes/tour.routes.js";
import regionRouter from "./routes/region.routes.js";
import stateRouter from "./routes/state.routes.js";
import cityRouter from "./routes/city.routes.js";
import moodRouter from "./routes/mood.routes.js";
import durationRouter from "./routes/duration.routes.js";
import cookie from "cookie-parser";
const app = express();

app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cookie());
app.use("/api/auth", authRouter);
app.use("/api/region", regionRouter);
app.use("/api/tours", tourRouter);
app.use("/api/state", stateRouter);
app.use("/api/city", cityRouter);
app.use("/api/mood", moodRouter);
app.use("/api/duration", durationRouter);
export default app;
